{{- if and .Values.site24x7Agent.create (not .Values.existingSecret.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "site24x7.fullname" . }}-agent
type: Opaque
data:
  KEY: {{ .Values.deviceKey | b64enc }}
{{- end }}
