registry: site24x7/docker-agent:release1800
apiversion: rbac.authorization.k8s.io/v1
kubeStateRegistry: quay.io/coreos/kube-state-metrics:v1.9.7
site24x7:
  device_key: ""
  http_proxy: ""
  https_proxy: ""
  display_name: ""
kubernetes:
  kube_state_metrics_url: ""
  kube_api_server_endpoint_url: ""
  namespace: default
